name: First Workflow

on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Step one
      run: echo "Log from Job 1, step one"
    - name: Step two
      run: echo "Log from Job 2, step two"
      
  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
    name: Step one
      run: echo "Log from job 2, step one"
    - name: Step two
      run: echo "Log from job 2, step two"